import { Dimensions, StyleSheet } from "react-native";
import Colors from "../../assets/Colors/Colors";

const productDetailsStyle = StyleSheet.create({
    pdView:{
        width:Dimensions.get('screen').width,
        minHeight:Dimensions.get('screen').height
    },
    backBtn:{
        position:'absolute',
        top:40,
        left:20,
        zIndex:5
    },
    quantityIcon:{
        borderWidth:1,
        borderColor:Colors.darkColor,
        borderRadius:22/2,
        width:22,
        textAlign:'center',
        textAlignVertical:'center'
    },
    prodImg:{
        width:'100%',
        height:Dimensions.get('screen').height*0.5
    },
    pdInfo:{
        backgroundColor:Colors.bgWhite,
        width:'100%',
        marginTop:-10,
        minHeight:Dimensions.get('screen').height*0.55,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        overflowX:'hidden',
        paddingTop:20,
        paddingBottom:20,
        paddingLeft:'5%',
        paddingRight:'5%',
        gap:10
    },
    pdInfoView:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        width:'100%'
    },
    pName:{
        fontFamily:'Bold',
        width:'70%',
        fontSize:20
    },
    pPrice:{
        fontFamily:'Bold',
        fontSize:16,
        backgroundColor:Colors.lightNavColor,
        padding:5,
        borderRadius:10,
        textAlign:'center',
        width:'30%',
        textAlignVertical:'center'
    },
    ratings:{
        flexDirection:'row',
        gap:2
    },
    ratingText:{
        fontFamily:'Medium',
        fontSize:16,
        textAlign:'center',
        textAlignVertical:'center',
        marginLeft:5
    },
    quantity:{
        flexDirection:'row',
        gap:10,
        justifyContent:'center',
        alignItems:'center',
    },
    quantityText:{
        fontFamily:'Medium',
        fontSize:16,
    },
    description:{
        gap:5
    },
    header:{
        fontSize:20,
        fontFamily:'Medium',
        textTransform:'capitalize'
    },
    descText:{
        fontSize:12,
        fontFamily:'Regular',
        textAlign:'justify'
    },
    purchase:{
        flexDirection:'row',
        gap:5,
        width:'100%',
        alignItems:'center'
    },
    buyBtn:{
        width:'100%',
        backgroundColor:'black',
        color:Colors.bgWhite,
        fontSize:20,
        fontFamily:'Bold',
        paddingLeft:10,
        paddingRight:10,
        paddingTop:2,
        borderRadius:20,
        textTransform:'uppercase',
        textAlignVertical:'center'
    },
    addToCart:{
        backgroundColor:'black',
        color:Colors.bgWhite,
        textAlign:'center',
        textAlignVertical:'center',
        padding:7,
        borderRadius:30
    }
})

export default productDetailsStyle;