import { Dimensions, StyleSheet } from "react-native";
import Colors from "../../assets/Colors/Colors";

const userStyle = StyleSheet.create({
    user:{
    },
    userBanner:{
        width:'100%',
        overflow:'hidden'
    },
    bannerImg:{
        width:Dimensions.get('screen').width,
        height:Dimensions.get('screen').height/3
    },
    userInfo:{
        paddingTop:60,
        paddingLeft:'5%',
        paddingRight:'5%',
        paddingBottom:80,
        position:'relative',
        gap:5,
        justifyContent:'center',
        alignItems:'center'
    },
    userImg:{
        width:100,
        height:100,
        borderRadius:100/2,
        borderColor:Colors.lightNavColor,
        borderWidth:2,
        position:'absolute',
        top:-50,
        left:Dimensions.get('screen').width/2 - 50,
    },
    loginText:{
        fontFamily:'Medium',
        textAlign:'center',
        fontSize:15
    },
    loginBtn:{
        fontFamily:'Regular',
        fontSize:15,
        textTransform:'uppercase',
        color:Colors.darkColor,
        backgroundColor:Colors.lightNavColor,
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:10,
        paddingRight:10,
        borderRadius:20,
        borderWidth:1,
        textAlign:'center',
        borderColor:Colors.navColorDark,
        textAlignVertical:'center'
    },
    login:{
        width:Dimensions.get('screen').width,
        paddingTop:10,
        paddingLeft:'5%',
        paddingRight:'5%',
        paddingBottom:80,
        gap:10,
        justifyContent:'center',
        alignItems:'center',
    },
    loginImg:{
        width:Dimensions.get('screen').width,
        height:Dimensions.get('screen').height/2.5,
        objectFit:'fill'
    },
    tagline:{
        fontFamily:'Bold',
        fontSize:25,
        color:Colors.darkColor,
        marginTop:20
    },
    loginForm:{
        width:'100%',
        gap:10
    },
    formComponent:{
        width:'100%'
    },
    label:{
        alignSelf:'flex-end',
        fontFamily:'Regular',
        fontSize:10,
        color:Colors.darkColor,
        textTransform:'capitalize'
    },
    formComponentTextField:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        gap:10,
        backgroundColor:Colors.lightNavColor,
        padding:10,
        borderRadius:5
    },
    textIput:{
        width:'80%',
        fontFamily:'Regular'
    },
    loginBtn2:{
        width:'100%',
        backgroundColor:Colors.darkColor,
        color:Colors.bgWhite,
        textAlign:'center',
        textAlignVertical:'center',
        paddingBottom:5,
        paddingTop:5,
        paddingLeft:10,
        paddingRight:10,
        fontFamily:'Bold',
        fontSize:20,
        textTransform:'uppercase',
        borderRadius:5,
        marginTop:20
    },
    registerBtn:{
        fontFamily:'Medium',
        fontSize:15,
        color:Colors.darkColor
    }
})

export default userStyle;